<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'title' => 'Stylish Jacket',
                'slug' => 'stylish-jacket',
                'description' => '<p>This jacket is made from high-quality materials, offering both comfort and durability. Perfect for casual outings or party.<br></p>',
                'short_description' => '<p>A stylish and comfortable jacket for woman.<br></p>',
                'shipping_returns' => '<p>Free shipping on orders over $50. </p><p>Easy returns within 30 days.<br></p>',
                'price' => 29.99,
                'compare_price' => 39.99,
                'category_id' => 2,
                'sub_category_id' => 5,
                'brand_id' => null,
                'is_featured' => 'yes',
                'sku' => 'WJT-001',
                'barcode' => '123456789012',
                'track_qty' => 'yes',
                'qty' => 100,
                'status' => 1,
                'created_at' => '2024-08-22 18:27:56',
                'updated_at' => '2024-08-22 18:27:56',
            ],
            [
                'id' => 2,
                'title' => 'MacBook Pro 14',
                'slug' => 'macbook-pro-14',
                'description' => '<p>The MacBook Pro 14 combines a lightweight design with powerful performance. Featuring a 14-inch Full HD display, Intel Core i7 processor, 16GB RAM, and 512GB SSD, it’s perfect for work and play on the go. Enjoy up to 12 hours of battery life, fast charging, and a backlit keyboard.<br></p>',
                'short_description' => '<p>A sleek and powerful 14-inch laptop designed for professionals.<br></p>',
                'shipping_returns' => '<p>Free shipping. </p><p>30-day money-back guarantee.<br></p>',
                'price' => 1199.99,
                'compare_price' => 1299.99,
                'category_id' => 1,
                'sub_category_id' => 2,
                'brand_id' => 1,
                'is_featured' => 'yes',
                'sku' => 'MAC-PRO-14',
                'barcode' => '987654321098',
                'track_qty' => 'yes',
                'qty' => 20,
                'status' => 1,
                'created_at' => '2024-08-22 18:37:25',
                'updated_at' => '2024-08-22 18:37:25',
            ],
            [
                'id' => 3,
                'title' => 'Canon EOS R6 Camera',
                'slug' => 'canon-eos-r6-camera',
                'description' => '<p>The Canon EOS R6 features a 20.1 MP Full-Frame CMOS sensor, 4K video recording, and Dual Pixel CMOS AF II. With up to 12 fps mechanical shutter and up to 20 fps electronic (silent) shutter, this camera is built for speed and precision. Ideal for professionals and enthusiasts alike.<br></p>',
                'short_description' => '<p>A versatile mirrorless camera perfect for both photography and videography.<br></p>',
                'shipping_returns' => '<p>Free shipping on orders over $500.</p><p> 30-day return policy.<br></p>',
                'price' => 2499.99,
                'compare_price' => 2699.99,
                'category_id' => 1,
                'sub_category_id' => 3,
                'brand_id' => 2,
                'is_featured' => 'yes',
                'sku' => 'CAN-EOS-R6',
                'barcode' => '123456789000',
                'track_qty' => 'yes',
                'qty' => 30,
                'status' => 1,
                'created_at' => '2024-08-22 18:40:42',
                'updated_at' => '2024-08-22 18:47:22',
            ],
            [
                'id' => 4,
                'title' => 'Office Chair',
                'slug' => 'office-chair',
                'description' => '<p>The Ergonomic Office Chair features adjustable height, lumbar support, and a reclining function. Upholstered in high-quality mesh fabric for breathability and comfort. Perfect for any home or office setup, this chair ensures proper posture and reduced strain during extended work sessions.<br></p>',
                'short_description' => '<p>A comfortable and adjustable office chair designed for long hours of work.<br></p>',
                'shipping_returns' => '<p>Free shipping on orders over $75. </p><p>30-day return policy with free returns.<br></p>',
                'price' => 179.99,
                'compare_price' => 199.99,
                'category_id' => 3,
                'sub_category_id' => 7,
                'brand_id' => null,
                'is_featured' => 'yes',
                'sku' => 'CHAIR-2024',
                'barcode' => '543216789012',
                'track_qty' => 'yes',
                'qty' => 10,
                'status' => 1,
                'created_at' => '2024-08-22 18:45:53',
                'updated_at' => '2024-08-22 18:45:53',
            ],
            [
                'id' => 5,
                'title' => 'Apple Watch Series 8',
                'slug' => 'apple-watch-series-8',
                'description' => '<p>The Apple Watch Series 8 features a sleek design with a large, always-on display. It includes advanced health monitoring capabilities like ECG, blood oxygen, and temperature sensors. With improved durability, fast charging, and seamless integration with iOS devices, it’s perfect for tracking your fitness, health, and daily activities.<br></p>',
                'short_description' => '<p>The latest Apple Watch with advanced health monitoring and fitness features.<br></p>',
                'shipping_returns' => '<p>Free shipping on all orders.</p><p> 30-day return policy with free returns.<br></p>',
                'price' => 399.99,
                'compare_price' => 499.99,
                'category_id' => 2,
                'sub_category_id' => null,
                'brand_id' => 1,
                'is_featured' => 'yes',
                'sku' => 'AP-WATCH-8',
                'barcode' => '678901234567',
                'track_qty' => 'yes',
                'qty' => 20,
                'status' => 1,
                'created_at' => '2024-08-22 18:53:51',
                'updated_at' => '2024-08-22 18:53:51',
            ],
        ]);

        DB::table('product_images')->insert([
            [
                'id' => 1,
                'product_id' => 1,
                'image' => '1724325988_66c720645a3b3.jpg',
                'sort_order' => 0,
                'created_at' => '2024-08-22 18:27:56',
                'updated_at' => '2024-08-22 18:27:56',
            ],
            [
                'id' => 2,
                'product_id' => 1,
                'image' => '1724325988_66c72064b6222.jpg',
                'sort_order' => 0,
                'created_at' => '2024-08-22 18:27:56',
                'updated_at' => '2024-08-22 18:27:56',
            ],
            [
                'id' => 3,
                'product_id' => 2,
                'image' => '1724326485_66c722559f2e2.jfif',
                'sort_order' => 0,
                'created_at' => '2024-08-22 18:37:25',
                'updated_at' => '2024-08-22 18:37:25',
            ],
            [
                'id' => 4,
                'product_id' => 2,
                'image' => '1724326563_66c722a39bc43.png',
                'sort_order' => 0,
                'created_at' => '2024-08-22 18:37:25',
                'updated_at' => '2024-08-22 18:37:25',
            ],
            [
                'id' => 5,
                'product_id' => 3,
                'image' => '1724326782_66c7237e980c7.jpg',
                'sort_order' => 0,
                'created_at' => '2024-08-22 18:40:42',
                'updated_at' => '2024-08-22 18:40:42',
            ],
            [
                'id' => 6,
                'product_id' => 4,
                'image' => '1724326994_66c72452b2c12.jpg',
                'sort_order' => 0,
                'created_at' => '2024-08-22 18:45:53',
                'updated_at' => '2024-08-22 18:45:53',
            ],
            [
                'id' => 7,
                'product_id' => 5,
                'image' => '1724327561_66c7268969e54.jpg',
                'sort_order' => 0,
                'created_at' => '2024-08-22 18:53:51',
                'updated_at' => '2024-08-22 18:53:51',
            ],
            [
                'id' => 8,
                'product_id' => 5,
                'image' => '1724327561_66c726896c91d.jpg',
                'sort_order' => 0,
                'created_at' => '2024-08-22 18:53:51',
                'updated_at' => '2024-08-22 18:53:51',
            ],
        ]);
    }
}
